version: '2'

services:
  redis:
    image: redis:latest
    container_name: ratelimit-redis
    expose:
      - 6379
    ports:
      - 6379:6379

  ratelimit:
    image: ${IMAGE_TAG}
    container_name: ratelimit
    links:
      - redis:redis
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=opt/application/conf
      - RUNTIME_SUBDIRECTORY=ratelimit
    expose:
      - 6070
      - 8080
      - 8081
    ports:
      - 6070:6070
      - 8080:8080
      - 8081:8081

